In [2]:
import numpy as np
from scipy import linalg

In [ ]:
#                 (0,244)--------(294,244)
#                     |               |
# Polygone ->         |               |
#                     |               |
#                   (0,0)--------(294, 0)

In [180]:
def getPMatrix(X, U):
    """
    REQUIRE:
    X = [[xw,yw],[xw2,yw2],...,[xwN,ywN]] - WORLD COORDS
    U = [[u,v],[u2,v2],...,[uN,vN]] - IMAGE COORDS

    will return calibration matrix of p_{i,i}
    """
    A = np.empty((len(X)*2, 12))

    for k, pointW, pointPX in zip(range(0, len(X), 2), X, U):
        xw = pointW[0]
        yw = pointW[1]
        zw = 1
        u = pointPX[0]
        v = pointPX[1]

        A[k] = np.array([xw, yw, zw, 1, 0, 0, 0, 0, -u*xw, -u*yw, -u*zw, -u])
        A[k+1] = np.array([0, 0, 0, 0, xw, yw, zw, 1, -v*xw, -v*yw, -v*zw, -v])

    A_T_A = np.dot(A.T, A)
    eigen_values, eigen_vectors = np.linalg.eig(A_T_A)
    eigen_vector_min = eigen_vectors[:, np.argmin(eigen_values)]
    return np.reshape(eigen_vector_min.real, (3, 4))

def getRealCoords(A, pt):
    b = np.append(np.array(pt), 1)
    return np.linalg.lstsq(A, b, rcond=None)[0]


pol1 = (582/1280, 271/720)
pol1_2 = (486/1280, 384/720)
pol2 = (371/1280, 520/720)
pol2_2 = (614/1280, 601/720)
pol3 = (945/1280, 710/720)
pol3_2 = (976/1280, 471/720)
pol4 = (994/1280, 317/720)
pol4_2 = (764/1280, 290/720)
pol_c = (710/1280, 422/720)


x_res, y_res = (1920, 1080)# resolution
polygon = np.array([(pol1[0] * x_res, pol1[1] * y_res), 
                    (pol1_2[0] * x_res, pol1_2[1] * y_res), 
                    (pol2[0] * x_res, pol2[1] * y_res),
                    (pol2_2[0] * x_res, pol2_2[1] * y_res),
                    (pol3[0] * x_res, pol3[1] * y_res),
                    (pol3_2[0] * x_res, pol3_2[1] * y_res),
                    (pol4[0] * x_res, pol4[1] * y_res), 
                    (pol4_2[0] * x_res, pol4_2[1] * y_res),
                    (pol_c[0] * x_res, pol_c[1] * y_res)], dtype=int)#points for polygone in the center

p_matrix = getPMatrix([(0, 244), (0,122), (0, 0), (147, 0), (294, 0), (294, 122), (294, 244), (147, 244), (147, 122)], polygon)

print(polygon)
print(p_matrix)
print(np.dot(p_matrix, [0, 0, 1, 1]))

[[ 873  406]
 [ 729  576]
 [ 556  780]
 [ 921  901]
 [1417 1065]
 [1464  706]
 [1491  475]
 [1146  435]
 [1065  633]]
[[-5.07965128e-09 -6.18782465e-09  3.04899151e-06 -4.75419602e-06]
 [-4.03091396e-11  3.67687354e-09  7.07105585e-01 -7.07107977e-01]
 [ 2.75357622e-12 -2.52367998e-12 -1.53345200e-09 -1.53345195e-09]]
[-1.70520451e-06 -2.39237042e-06 -3.06690395e-09]
