In [7]:
import numpy as np
from scipy import linalg
from scipy.optimize import minimize

In [8]:
#                 (0,244)--------(294,244)
#                     |               |
# Polygone ->         |               |
#                     |               |
#                   (0,0)--------(294, 0)

Zhang’s Calibration DLT METHOD

In [9]:
pol1 = (554/1280, 237/720)
pol2 = (343/1280, 490/720)
pol3 = (934/1280, 693/720)
pol4 = (978/1280, 278/720)
pol1_2 = (461/1280, 349/720)
pol2_2 = (583/1280, 572/720)
pol3_2 = (961/1280, 438/720)
pol4_2 = (727/1280, 254/720)


x_res, y_res = (1920, 1080)# resolution
polygon = np.array([(pol1[0] * x_res, pol1[1] * y_res), 
                    (pol1_2[0] * x_res, pol1_2[1] * y_res), 
                    (pol2[0] * x_res, pol2[1] * y_res),
                    (pol2_2[0] * x_res, pol2_2[1] * y_res),
                    (pol3[0] * x_res, pol3[1] * y_res),
                    (pol3_2[0] * x_res, pol3_2[1] * y_res),
                    (pol4[0] * x_res, pol4[1] * y_res), 
                    (pol4_2[0] * x_res, pol4_2[1] * y_res)], dtype=int)#points for polygone in the center

def zang(pt):
    
    pointsW = [(0, 244), (0,122), (0, 0), (147, 0), (294, 0), (294, 122), (294, 244), (147, 244)]
    pointsPX = polygon
    print(pointsW, '\n', pointsPX)

    if len(pointsPX) != len(pointsW): return

    A = np.zeros((len(pointsW)*2, 9))
    for k, W, PX in zip(range(0, len(pointsW)*2, 2),pointsW, pointsPX):
        xw = W[0]
        yw = W[1]

        u = PX[0]
        v = PX[1]

        A[k] = [-xw, -yw, -1, 0, 0, 0, u*xw, u*yw, u]
        A[k+1] = [0, 0, 0, -xw, -yw, -1, v*xw, v*yw, v]
    
    U,D,V = np.linalg.svd(A)
    m_ext = np.reshape(V[-1] / V[-1][-1], (3,3))
    vector = np.array([pt[0], pt[1], 1])
    print(m_ext)
    #BACKWARD PIXEL -> WORLD
    result = np.linalg.solve(m_ext, vector)
    result = result / result[-1]
    print(result[:2])

    #FORWARD WORLD -> PIXEL
    # result = np.dot(m_ext, vector)
    # result = result / result[-1]
    # print(result)

zang([1146, 435])

[(0, 244), (0, 122), (0, 0), (147, 0), (294, 0), (294, 122), (294, 244), (147, 244)] 
 [[ 831  355]
 [ 691  523]
 [ 514  735]
 [ 874  858]
 [1401 1039]
 [1441  657]
 [1467  417]
 [1090  381]]
[[ 1.34649732e+00  2.63158080e+00  5.17662265e+02]
 [-2.07245855e-01 -9.66656408e-01  7.39496589e+02]
 [-1.18351294e-03  1.67921001e-03  1.00000000e+00]]
[177.12991014 211.52313345]
